---
- hosts: docker_servers
  become: true
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull the latest Docker image
      command: docker pull nguyen1611/myapp:latest

    - name: Stop and remove existing container
      command: >
        docker rm -f myapp
      ignore_errors: true

    - name: Run the Docker container
      command: >
        docker run -d --name myapp -p 80:80 nguyen1611/myapp:latest
